sanitybot/auth.py
import re
from flask import Blueprint, render_template, url_for,  request, flash, redirect
from werkzeug.utils import redirect
from .models import Admin, User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)



# USER LOGIN
@auth.route('/', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.chat'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
        
    return render_template("login.html", user=current_user)

# USER REGISTRATION
@auth.route('/register', methods = ['GET', 'POST'])
def register():   
    if request.method == 'POST':
        firstname = request.form.get('signup_first_name')
        lastname = request.form.get('signup_last_name')
        email = request.form.get('signup_email')
        password = request.form.get('signup_password')
        cpassword = request.form.get('signup_cpassword')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif password != cpassword:
            flash('Password and confirm password does not match.', category='error')
        else:
            new_user = User(firstname=firstname, lastname=lastname, email=email, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            # login_user(user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))

    return render_template("signup.html", user=current_user)

# FORGET PASSWORD - USER
@auth.route('/forgotpassword', methods = ['GET', 'POST'])
def forgotpassword(): 
    if request.method == "POST":
        email_text = request.form['emailr']
        pword = request.form['new_password']
        cpword = request.form['cpassword']

        if pword != cpword:
            flash('Password and Confirm password does not match.', category='error')
            return redirect(url_for('auth.forgotpassword'))
        else:
            user = User.query.filter_by(email=email_text).first()
            user.password = generate_password_hash(pword, method='sha256')
        
            # update database
            try:
                db.session.commit()
                flash('Update password successfully!', category= 'success')
                return redirect(url_for('auth.login'))
            except:
                return 'ERROR'
    else:
        return render_template("forgotpassword.html")


    

# LOGOUT USER
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


# ADMIN LOGIN
@auth.route('/adminlogin', methods = ['GET', 'POST'])
def admin():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        admin = Admin.query.filter_by(username=username).first()
        if admin:
            if check_password_hash(admin.password, password):
                login_user(admin, remember=True)
                return redirect(url_for('views.dashboard'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist.', category='error')
        
    return render_template("admin_login.html", user=current_user)



# LOGOUT ADMIN
@auth.route('/logoutadmin')
@login_required
def adminlogout():
    logout_user()
    return redirect(url_for('auth.admin'))


@auth.route('/login')
def signin():
    return render_template("login.html")

sanitybot/views.py
from flask import Blueprint, render_template, url_for,  request, flash, redirect
from nltk.featstruct import _trace_unify_fail
from werkzeug.utils import redirect
from .models import Admin, User, User_health
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, current_user
from datetime import date
from flask import session
# from chat import chat
from chat import get_response

views = Blueprint('views', __name__)

# homepage
@views.route('/home',  methods = ['GET','POST'])
@login_required
def home():
    if request.method == 'POST':
        firstname = request.form.get('firstname')
        middlename = request.form.get('middlename')
        lastname = request.form.get('lastname')
        address = request.form.get('address')
        contact = request.form.get('contact')
        date_submit = date.today()
        condition = request.form.get('condition')
        
    else:       
        # Get logged in user
        user = current_user
        return render_template('home.html', user=user)

# user profile
@views.route('/profile', methods = ['GET', 'POST'])
@login_required
def profile():
    if request.method == "POST":
        id = request.form['id']

        user = User.query.filter_by(id=id).first()
        user.firstname = request.form['firstname']
        user.middlename = request.form['middlename']
        user.lastname = request.form['lastname']
        user.address = request.form['address']
        user.contact = request.form['contact']
        user.email = request.form['email']
        
        # update database
        try:
            db.session.commit()
            flash('Update successfully!', category= 'success')
            return redirect(url_for('views.profile'))
        except:
            return 'ERROR'
    else:
        # Get logged in user
        user = current_user
        return render_template('userprofile.html', user=user)

#edit user profile security
@views.route('/profileupdate', methods = ['GET' , 'POST'])
def profile_security():
    if request.method == "POST":
        user = current_user
        pword = request.form['newpassword']
        rpword = request.form['retypepass']

        if pword != rpword:
            flash('Password and Retype password does not match.', category='error')
            return redirect(url_for('views.profile_security'))
        else:
            user = User.query.filter_by(id=user.id).first()
            user.password = generate_password_hash(pword, method='sha256')
        
            # update database
            try:
                db.session.commit()
                flash('Update successfully!', category= 'success')
                return redirect(url_for('views.profile'))
            except:
                return 'ERROR'
    else:
        # Get logged in user
        user = current_user
        return render_template('changepassword.html', user=user)

# ADMIN HOME DASHBOARD
@views.route('/dashboard' , methods = ['GET' , 'POST'])
def dashboard():
    users = User.query.all()
    return render_template("controlpanel.html", users=users)

# ADMIN PROFILE
@views.route('/adminprofile',  methods = ['GET', 'POST'])
def admin_profile():
    if request.method == 'POST':
        username = request.form.get('uname')
        email = request.form.get('email')
        pword = request.form.get('pword')
        cpword = request.form.get('re-pword')

        user = Admin.query.filter_by(email=email).first()
        if user:
            flash('Email already exists. Try other email.', category='error')
        elif pword != cpword:
            flash('Password and confirm password does not match.', category='error')
        else:
            new_user = Admin(username=username, email=email, password=generate_password_hash(pword, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            # login_user(user, remember=True)
            flash('Admin account added!', category='success')
            return redirect(url_for('views.admin_profile'))

    users = Admin.query.all()
    return render_template("admin_manageaccounts.html", users=users)

# ADMIN edit profile
@views.route('/edit/<int:id>', methods = ['GET' , 'POST'])
def edit(id):    
    user = Admin.query.get_or_404(id)
    if request.method == 'POST':
        user.username = request.form['uname']
        user.email = request.form['email']
        password = request.form['pword']
        rpword = request.form['re-pword']

        if password != rpword:
            flash('Password and Retype password does not match.', category='error')
            return redirect(url_for('views.admin_profile'))
        else:
            user = Admin.query.get_or_404(id)
            user.password = generate_password_hash(password, method='sha256')
      
        # update database
            try:
                db.session.commit()
                flash('Update successfully!', category= 'success')
                return redirect(url_for('views.admin_profile'))
            except:
                    return 'ERROR'
    else:
        return render_template('editAdmin.html', user=user)

# ADMIN patient info
@views.route('/patientprofile', methods = ['GET','POST'])
def admin_patients():
    users = User.query.all()
    return render_template("admin_patients.html", users=users)

# DELETE
@views.route('/delete/<int:id>')
def delete(id):
    user = Admin.query.get_or_404(id)

    try:
        db.session.delete(user)
        db.session.commit()
        return redirect(url_for('views.admin_profile'))
    except:
        return 'Error'

@views.route('/search')
def search():
        if request.method == 'POST':
            users = User.query.all()
            search_value = request.form['search']
            search = "%{0}%".format(search_value)
            results = users.query.filter(users.firstname.like(search)).all()
            return render_template("admin_patients.html", users=results)
        else:
            # Get logged in user
            user = current_user
            return render_template("admin_patients.html", users=user)

@views.route('/chat', methods = ['GET', 'POST'])
def chat():
    user = current_user
    return render_template('chat.html', data={'user': user})

@views.route('/welcome', methods = ['GET', 'POST'])
def welcome():
    user = current_user
    return render_template('welcomepage.html', user=user)

@views.route('/postpartum', methods = ['GET', 'POST'])
def postpartum():
    user = current_user
    return render_template('postpartum.html', user=user)

@views.route('/sanity', methods = ['GET', 'POST'])
def sanity():
    user = current_user
    return render_template('sanity.html', user=user)

@views.route('/aboutpostpartum', methods = ['GET', 'POST'])
def aboutpostpartum():
    user = current_user
    return render_template('about_postpartum.html', user=user)
    
@views.route('/welcomeback', methods = ['GET', 'POST'])
def home2():
    user = current_user
    return render_template('home2.html', user=user)

@views.route('/loading', methods = ['GET', 'POST'])
def loading():
    return render_template('splash_screen.html')

@views.route('/result', methods = ['GET', 'POST'])
def result():
    user = current_user
    # answers = request.get_json().get("message")
    # print(answers)
    return render_template('result.html', user=user)

sanitybot/templates/about_postpartum.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/style_welcome.css') }}" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>SanityBot | Postpartum</title>
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert-error" role="alert">
        {{ message }}
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
      {% else %}
      <div class="alert-success" role="alert">
        {{ message }}
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
    <main>
       <!-- landingpage -->
       <div class="wrapper light scroll-bar">
        <header>
          
          <div class="container">
            <div class="logo">
              <img class="logo_img" src="{{ url_for('static', filename='/images/robot_logo.svg') }}" alt="logo">
              <h3>SanityBot</h3>
            </div>
            <div class="links">
              <ul class="main">
                <li><a href="{{ url_for('views.home') }}">Home</a></li>
                <li><a href="{{ url_for('views.sanity') }}">Sanity</a></li>
                <li><a href="{{ url_for('views.aboutpostpartum') }}"style="color:#46A2FF">Postpartum</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
              </ul>
              <ul>
                <li><a href="{{ url_for('views.profile') }}">{{ user.firstname }} {{ user.lastname }}</a></li>
              </ul>
            </div>

            <div class="overlay"></div>

            <div class="hamburger">
              <div class="bar"></div>
            </div>

          </div>
        </header>
      <div class="content-area">
          <div class="container2">
            <div class="left">
              <img src="{{ url_for('static', filename='/images/motherbaby.svg') }}" alt="Image" class="motherbaby">
            </div>
            <div class="right">
              <div class="title1">
                <h1>What is Maternal Health?</h1>
              </div>
              <p class="text1">
                Maternal health is described as the health and well-being of 
                a woman throughout its pregnancy, childbirth and postnatal 
                period that involves the states of women’s physical, mental, 
                emotional, and social health aspects.
              </p>
              <div class="title1">
              <h3>Why is it important?</h3>
              </div>
              <p class="text1">
                Access to quality maternal healthcare not only ensures a 
                mother's health, but it also helps to ensure the health of her
                newborn child and the rest of her family.
              </p>
            </div>
          </div>
        </div>
        <div class="content-area">
          <div class="container2">
            <div class="left">
              <div class="title1">
                <h1>What is Postpartum Depression?</h1>
              </div>
              <p class="text1">
                PPD is a complex mix of physical, emotional, 
                and behavioral changes that occur in some 
                women after giving birth. According to the 
                DSM-5, a manual used to diagnose mental 
                disorders, PPD is a form of major depression 
                that begins within 4 weeks after delivery.
              </p>
            </div>
            <div class="right rindex">
              <img src="{{ url_for('static', filename='/images/sademoji.svg') }}" alt="Image" class="sanity">
            </div>
          </div>
        </div>
            <div class="content-area">
              <div class="container2">
                <div class="left">
                  <img src="{{ url_for('static', filename='/images/motherdaugh.svg') }}" alt="Image" class="motherdaugh">
                </div>
                <div class="right">
                  <div class="title1">
                    <h1>Postpartum Depression Treatment</h1>
                  </div>
                  <p class="text1">
                    Postpartum depression is treated differently 
                    depending on the severity of the symptoms. 
                    Anti-anxiety or antidepressant medications, 
                    psychotherapy, and participation in a support 
                    group for emotional support and education are 
                    all treatment options.
                  </p>
                </div>
              </div>
            </div>
            <div class="content-area">
              <div class="container2">
                <div class="left">
                  <div class="title1">
                    <h1>Types of Postpartum Depression</h1>
                  </div>
                  <p class="text1">
                    Three terms are used to describe the mood 
                    changes that women can experience after 
                    giving birth:
                  </p>
                  <ol class="text2">1. Baby Blues</ol>
                  <ol class="text2">2. Postpartum Depression (PPD)</ol>
                  <ol class="text2">3. Postpartum Psychosis</ol>
                </div>
                <div class="right rindex">
                  <img src="{{ url_for('static', filename='/images/motherchild.svg') }}" alt="Image" class="sanity">
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- landing page end -->        
       </div>
    </main>
  </body>
</html>

sanitybot/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/style_changepass.css') }}" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Sanitybot | Change Password</title>
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert-error" role="alert">
        {{ message }}
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
      {% else %}
      <div class="alert-success" role="alert">
        {{ message }}
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
    <main>

       <!-- profilepage -->
       <div class="wrapper light">
        <header>        
          <div class="container">
            <div class="logo">
              <img class="logo_img" src="{{ url_for('static', filename='/images/robot_logo.svg') }}" alt="logo">
              <h3>SanityBot</h3>
            </div>
            <div class="links">
              <ul class="main">
                <li><a href="{{ url_for('views.home') }}">Home</a></li>
                <li><a href="{{ url_for('views.sanity') }}">Sanity</a></li>
                <li><a href="{{ url_for('views.aboutpostpartum') }}">Postpartum</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
              </ul>
              <ul>
                <li><a href="{{ url_for('views.profile') }}"style="color:#46A2FF">{{ user.firstname }} {{ user.lastname }}</a></li>
              </ul>
            </div>

            <div class="overlay"></div>

            <div class="hamburger">
              <div class="bar"></div>
            </div>

          </div>
        </header>

        <div class="container1">
            <form action="" method="post">
                <div class="row">        
                    <div class="col">
                        <h3 class="title">Change Password</h3>
                        <div class="inputBox1">
                            <span>Current Password:</span>
                            <input type="password" placeholder="Password" name="password" value= {{ user.password }}>
                        </div>
                        <div class="inputBox1">
                            <span>New Password:</span>
                            <input type="password" placeholder="Password" name="newpassword">
                        </div>
                        <div class="inputBox1">
                            <span>Re-type Password:</span>
                            <input type="password" placeholder="Password" name="retypepass">
                        </div>
                        <div class="flex-button">
                        <input type="submit" value="Save Changes" class="submit-btn" name="security_save">
                        <a href="{{ url_for('views.profile') }}" class="btnChange">Cancel</a>
                    </div>
                    </div>
                </div>
            </form>
        </div>    
        <!-- profile page end -->     
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </body>
</html>

sanitybot/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='/css/style_chatbot.css') }}" />
  <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>SanityBot | Home</title>
</head>

<body>
  <!-- LOADING HERE -->
  <div id="loading" data-isloading="true" style="background-color:#c3c3c3; width:100vw; height:500vh;">
    <div>
      <img class="sanitybot_img" src="{{ url_for('static', filename='/images/loading.svg') }}" alt="logo">
      <h2 class="tagline">An AI chatbot that makes you feel heard</h2>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if
  messages %} {% for category, message in messages %} {% if category ==
  'error' %}
  <div class="alert-error" role="alert">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  </div>
  {% else %}
  <div class="alert-success" role="alert">
    {{ message }}
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  </div>
  {% endif %} {% endfor %} {% endif %} {% endwith %}
  
  <main>
    <!-- landingpage -->
    <div class="wrapper light">
      <header>
        <div class="container">
          <div class="logo">
            <img class="logo_img" src="{{ url_for('static', filename='/images/robot_logo.svg') }}" alt="logo">
            <h3>SanityBot</h3>
          </div>
          <div class="links">
            <ul class="main">
              <li><a href="{{ url_for('views.home') }}" style="color:#46A2FF">Home</a></li>
              <li><a href="{{ url_for('views.sanity') }}">Sanity</a></li>
              <li><a href="{{ url_for('views.aboutpostpartum') }}">Postpartum</a></li>
              <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
            <ul>
              <li class="dropdown">
                <a href="#">{{ user.firstname }} {{ user.lastname }}</a>
                <div class="dropdown-content">
                  <a href="{{ url_for('views.profile') }}">View Profile</a>
                  <a class="toggle-btn">Dark Mode</a>
                  <a href="{{ url_for('auth.logout') }}">Logout</a>
                </div>
              </li>
            </ul>
          </div>
          <div class="overlay"></div>
          <div class="hamburger">
            <div class="bar"></div>
          </div>
        </div>
      </header>

      <div class="content-area">
        <div class="container">
          <div class="left">
            <div class="welcome">
              <img src="{{ url_for('static', filename='/images/welcome.svg') }}" alt="Image" class="sanity">
            <p class="text">
              Your AI friend. I am excited to talk to you  for the first time. I am here to help about your mental health concerns. 
            </p>
            </div>
            <!-- chatbot -->
            <div>
              {% if user.is_assess %}
              <a href="{{ url_for('views.chat') }}" class="btn_form">Talk to Sanity</a>
              {% else %}
              <a href="#" class="btn_form" id="show-modal">Talk to Sanity</a>
              {% endif %}

              <div class="modal">
                <div class="modal-box">
                  <div type="button" class="icon" id="hide-modal">
                    <i class="fa fa-times"></i>
                  </div>
                  <img class="logo_img1" src="{{ url_for('static', filename='/images/robot_logo.svg') }}" alt="logo">
                  <div class="modaltext">
                    Hello There! I am Sanity, your AI friend. I hope you'll find joy talking to me. Thank you!
                  </div>
                  <a href="{{ url_for('views.chat') }}" class="btn_form">Okay</a>
                </div>
              </div>
            </div>
            <!-- end chatbot -->
      <!-- landing page end -->
    </div>
  </main>
  </main>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="../static/app-chatbot.js"></script>
  <script>
    $(document).ready(function () {
      $('#show-modal').on('click', function () {
        $('.modal').css({ 'visibility': 'visible', 'opacity': '1' });
      });
      $('.modal .modal-box .icon i').on('click', function () {
        $('.modal').css({ 'visibility': 'hidden', 'opacity': '0' });
        clearAll();
      });
    }); 
  </script>

  <!-- LOADING HERE -->
  <script>
    isLoaded = false;
    const loadingElement = document.querySelector("#loading");

    if (!isLoaded) {
      if (loadingElement.getAttribute("data-isloading") === "true") {
        setTimeout(() => { loadingElement.style.display = "none"; }, 20000)
      }
      isLoaded = true;
    }

  </script>
  <script>
  
  $(document).ready(function() {
    $('.dropdown').click(function() {
      $(this).children('.dropdown-content').toggle();
    });

    $(document).click(function(event) {
      if (!$(event.target).closest('.dropdown').length) {
        $('.dropdown-content').hide();
      }
    });
  });
  
  </script>
</body>

</html>

sanitybot/templates/home2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/style_chatbot.css') }}" />
    <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>SanityBot | Welcome Back</title>
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      <div class="alert-error" role="alert">
        {{ message }}
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
      {% else %}
      <div class="alert-success" role="alert">
        {{ message }}
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
    <main>
       <!-- landingpage -->
       <div class="wrapper light">
        <header>
          <div class="container">
            <div class="logo">
              <img class="logo_img" src="{{ url_for('static', filename='/images/robot_logo.svg') }}" alt="logo">
              <h3>SanityBot</h3>
            </div>
            <div class="links">
              <ul class="main">
                <li><a href="{{ url_for('views.home') }}"style="color:#46A2FF">Home</a></li>
                <li><a href="{{ url_for('views.sanity') }}">Sanity</a></li>
                <li><a href="{{ url_for('views.aboutpostpartum') }}">Postpartum</a></li>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
              </ul>
              <ul>
                <li class="dropdown">
                  <a href="{{ url_for('views.profile') }}">{{ user.firstname }} {{ user.lastname }}</a></li>
                  <div class="dropdown-content">
                    <a href="#">Service 1</a>
                    <a href="#">Service 2</a>
                    <a href="#">Service 3</a>
                  </div>
              </ul>
            </div>
            <div class="overlay"></div>
            <div class="hamburger">
              <div class="bar"></div>
            </div>
          </div>
        </header>

        <div class="content-area">
          <div class="container">
            <div class="left">
              <div class="title">
                <h3>Are you not happy</h3>
                <h3>talking to</h3>
                <h1>Sanity?</h1>
              </div>
              <p class="text">
                An Artificial Intelligence Chatbot that helps you in 
                your psychological, emotional and social well-being. 
                Sanity makes you feel heard.
              </p>

              <!-- chatbot -->
              <div>
                {% if user.is_assess %}
                <a href="{{ url_for('views.chat') }}" class="btn_form">Start a new conversation</a>
                {% else %}
                <a href="#" class="btn_form" id="show-modal">Start a new conversation</a>
                {% endif %}

                <div class="modal">
                  <div class="modal-box">
                    <div type="button" class="icon" id="hide-modal">
                      <i class="fa fa-times"></i>
                    </div>
                    <img class="logo_img1" src="{{ url_for('static', filename='/images/robot_logo.svg') }}" alt="logo">
                    <div class="modaltext">
                      Hello There! I am Sanity, your AI friend. I hope you'll find joy talking to me. Thank you! 
                    </div>
                    <a href="{{ url_for('views.chat') }}" class="btn_form" >Okay</a>
                  </div>
                </div>
              </div>
              <!-- end chatbot -->

            </div>
            <div class="right">
              <img src="{{ url_for('static', filename='/images/homepage.svg') }}" alt="Image" class="sanity">
            </div>
          </div>
        </div>
        <!-- landing page end -->
      </div>
    </main>
  </main>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script>
    $(document).ready(function(){
    $('#show-modal').on('click', function(){
      $('.modal').css({'visibility': 'visible', 'opacity': '1'});
    });
    $('.modal .modal-box .icon i').on('click', function(){
      $('.modal').css({'visibility': 'hidden', 'opacity': '0'});
      clearAll();
    });
  }); 
    </script>
  </body>
</html>